### ISSUE TITLE
<title>タグが存在しないファイルへの対応

### ISSUE THREAD

**Issue by lyzon-sasaki** [akiraiwabuchi/index-generator#20]
<title>タグが存在しないファイルがあるとき、次のようなメッセージが出るため、機能が停止する。

```bash
C:\Git\***\Design\node_modules\index-generator\index.js:74
                                        title = title[0].replace(/<title>/g, '').replace(/<\/title>/g, '');
                                                     ^

TypeError: Cannot read property '0' of null
    at fs.readdir (E:\Git\***\Design\node_modules\index-generator\index.js:74:19)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "index" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

改善の提案：

1. 存在しないファイルは無視する。
2. 存在しないファイルは仮の名前（サイト名など）を付与する。

**Comment by akiraiwabuchi** [comment]
titleタグがない場合はファイル名から.htmlを切り取ったものを表示するよう修正。
https://github.com/akiraiwabuchi/index-generator/commit/1be388bbbeff306c84448ef77e4a360f558a516c
